### ISSUE TITLE
Public directory missing (index.php / .htaccess)

### ISSUE THREAD

**Issue by xPand4B** [rginnow/Valet-Dashboard#6]
You've exluded everything inside the `/public`directory inside the root `.gitignore`.

At could exclude generated stuff like the `app.{js|css}` files but ***not the `index.php` and `.htaccess` files***!!

**Comment by rginnow** [comment]
You are right! (Whoops!)

I'll update this tonight.

**Comment by xPand4B** [comment]
@rginnow Just a brief reminder here ^^

**Comment by rginnow** [comment]
@xPand4B Hey I've just pushed the update to get the public folder back in. I'm so sorry it took so long, but I've been away from all my side projects for a seriously long time, and I'm trying to get back into them this summer.

Thanks for the reminder. Let me know if you find anything else wrong, or have suggestions.

I do think I'm going to upgrade this to Laravel 8 at some point too, and bring all the dependencies up to speed, including Tailwind.

**Comment by xPand4B** [comment]
No Problemo, great to have you back here! :) @rginnow
